name: Sync-github-repo

on:
  - push
  - delete

jobs:
  sync:
    runs-on: indels-runner
    name: Git Repo Sync
    steps:
      - run: git remote rm target
        continue-on-error: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://git.indels.tech/Drivee/flipt-php.git
          target-username: ${{ secrets.GITLAB_ADMIN_USER }}
          target-token: ${{ secrets.GITLAB_ADMIN_GITHUB_SYNC_TOKEN }}
